### ISSUE TITLE
quant it revew

### ISSUE THREAD

**Issue by adina** [germs-lab/SOPs#12]
https://github.com/germs-lab/SOPs/blob/master/DNA_SOPs/Quant-iT_dsDNA_Assay.md

Some comments.

**Comment by LanyingMa** [comment]
done with this one

**Comment by adina** [comment]
Small one -

Pour the working solution into a new reservoir [what is this? a new container?, why? or for the multihannel; it is just a container to be easier to transfer sample by multichannel]. Use multiple channel pipettes to load 200 ul to targeted wells.

**Comment by LanyingMa** [comment]
"it is just a container to be easier to transfer sample by multichannel” is my answer to your questions.  i think they all know what it is.

**Comment by LeighAnnLong** [comment]
Lanying – Do be as specific as you can, since you will have dumb/inexperienced folks (like me) trying to use these SOPs without you there to ask.


-          Leigh Ann
