### ISSUE TITLE
Title change?

### ISSUE THREAD

**Issue by adina** [germs-lab/SOPs#2]
Is this a sop for teaching about Wafergen background?  Can we be more specific for the file name?  I'm having trouble telling what SOP is for what -- alternately, let's start using a folder within the SOP called Wafergen?

**Comment by adina** [comment]
@metajinomics

**Comment by metajinomics** [comment]
No, I am not going to use the SOP for teaching wafergen background. There is only one file Wafergen.md talking about wafergen. I am not sure if it is a good idea to make folder only for one file. But I am very happy to change name if the Wafergen.md sounds misleading. Could you suggest better name? Again, I am deeply apologize for making non specific name.. and not making a folder..
