### ISSUE TITLE
clarification on plate layout

### ISSUE THREAD

**Issue by adina** [germs-lab/SOPs#7]
@LanyingMa I'm a confused on the marked part here:  https://github.com/germs-lab/SOPs/blob/master/wafergen_SOPs/wafergen-plate-layout.md

Can we get this clarified and then we can have the layout SOP approved?

Thanks!

**Comment by LanyingMa** [comment]
I think the main reason is you are confused with assay and primer set.. in Wafergen, assay equals to primer set, does not equal to "Each assay is 1 probe and 1 sample”. i will try to clarify it.. i though the original one explains the this part.. i will try to clarify it.  i like the email template.

**Comment by adina** [comment]
@LanyingMa Can you take a final review, there are some additions I ask for -- specifically also where we are going to store the layouts for downloading.  We can even place those in Git if you decide that is a better place.

**Comment by LanyingMa** [comment]
I already put the layout link in the protocol, which are in Box.. i think it is ok to be in Box
